# Default values for faultline
# This is a YAML-formatted file.

global:
  namespace: faultline

otelCollector:
  image:
    repository: otel/opentelemetry-collector-contrib
    tag: 0.108.0
  service:
    type: ClusterIP
    port: 4318

grafana:
  image:
    repository: grafana/grafana-enterprise
    tag: 11.2.0
  adminPassword: admin
  service:
    type: ClusterIP
    port: 3000

prometheus:
  image:
    repository: prom/prometheus
    tag: v2.54.1
  service:
    type: ClusterIP
    port: 9090

loki:
  image:
    repository: grafana/loki
    tag: 3.1.0
  service:
    type: ClusterIP
    port: 3100

tempo:
  image:
    repository: grafana/tempo
    tag: 2.6.0
  service:
    type: ClusterIP
    port: 3200
